version: '2'
services:
  web:
    build: .
    restart: always
    #command: gunicorn -w 4 --reload -b localhost:5000 app:app
    command: python app.py
    ports:
     - "5000:5000"
    volumes:
     - ./web:/web